---
apiVersion: v1
kind: Service
metadata:
  name: api-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
