apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: gyanesh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class