apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gyanesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gyaneshtiwari/3-tier-api:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/api/appsettings.json"
              subPath: appsettings.json
              readOnly: true
          env:
            - name: ConnectionStrings__Basic3Tier
              value: "Host=db-clusterip-service;Port=5432;Database=basic3tier;Username=postgres;Password=admin123"
      volumes:
        - name: config
          configMap:
            name: config-map
            items:
              - key: appsettings.json
                path: appsettings.json